name: smart_cleaner_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.3
  animate_do: ^3.3.4
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^8.0.5
#  firebase_core: ^3.4.0
  geolocator:
  provider:
  flutter_spinkit:
  google_maps_flutter: ^2.6.1
  map_picker:
  geocoding:
  pinput:
  get:
  get_storage:
  #//Firebase//
  firebase_core:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  firebase_database:
  bcrypt: ^1.1.3
  #  Render After Effects animations natively on Flutter. This package is a pure Dart implementation of a Lottie player.
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
